services:
  rentx_database:
    image: postgres
    container_name: rentx_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=dorinha
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - asgard

  rentx_api:
    build: .
    container_name: rentx_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - asgard

volumes:
  pgdata:
    driver: local

networks:
  asgard:
