version: "3.8"

services:
  rentx_database:
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/postgres/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=dorinha
      - POSTGRES_DB=rentx

  # rentx_api:
  #   build: .
  #   container_name: api_rentx
  #   restart: always
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - rentx_database

volumes:
  pgdata:
    driver: local
