services:
  rentx_database:
    image: postgres
    container_name: rentx_database
    restart: always
    expose:
      - 5432
    # ports:
    # - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=dorinha
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  rentx_api:
    build: .
    container_name: rentx_api
    expose:
      - 3333
    # ports:
    # - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - rentx_database
    network_mode: host

volumes:
  pgdata:
    driver: local
